INSERT INTO figuras (FIG_TIPO, FIG_NOMBRE, FIG_LADO) VALUES (1, 'cua1', 10.0);
INSERT INTO figuras (FIG_TIPO, FIG_NOMBRE, FIG_RADIO) VALUES (2, 'cir1', 10.0);
INSERT INTO figuras (FIG_TIPO, FIG_NOMBRE, FIG_BASE, FIG_ALTURA) VALUES (3, 'rect1', 12.3 , 8.4);
INSERT INTO figuras (FIG_TIPO, FIG_NOMBRE, FIG_BASE, FIG_ALTURA) VALUES (4, 'triangulo1', 10.0, 8.4);
INSERT INTO figuras (FIG_TIPO, FIG_NOMBRE, FIG_LADO, FIG_NUMLADOS, FIG_APOTEMA) VALUES (5, 'poig1', 10.0, 6, 6.2);